language: python
python:
  - "3.4"
services:
  - postgresql
  - elasticsearch
cache:
  - pip
env:
  - CFLAGS=-O0
install:
  - pip install -U pip wheel
  - pip install coveralls
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database jeito;' -U postgres
  - cp jeito/settings_travis.py jeito/settings_local.py
script:
  - flake8
  - coverage run manage.py test
after_success:
  - coveralls
