version: '2'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=jeito
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  elasticsearch:
    image: elasticsearch:5.1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  tika:
    image: logicalspark/docker-tikaserver
    ports:
      - "9998:9998"
  django:
    build: .
    volumes:
      - .:/home/django
      - ./data/django:/home/django/var
    ports:
      - "8000:8000"
    links:
      - postgres
